cloud :
 aws :
   region :
     static : eu-north-1
   credentials :
     access-key : AKIAQITXKM3MUJ3MAPAQ
     secret-key : 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
   end-point :
     uri : https://sqs.eu-north-1.amazonaws.com/018503853785/SQSexample
